apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.serviceAccountName }}
    app.kubernetes.io/component: {{ .Values.serviceAccountName }}
    app.kubernetes.io/part-of: logging