apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-event-generator
  labels:
    app.kubernetes.io/name: kube-event-generator
    app.kubernetes.io/component: kube-event-generator
    app.kubernetes.io/part-of: logging
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-event-generator
  strategy:
    rollingUpdate:
      maxSurge: 25
      maxUnavailable: 25
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: k8s-event-generator
        app.kubernetes.io/component: k8s-event-generator
        app.kubernetes.io/part-of: logging
    spec:
      serviceAccountName: k8s-event-generator
      containers:
        - name: kube-event-generator
          image: ghcr.io/netcracker/kube-event-generator:main
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: COUNT
              value: "30"
            - name: SLEEP
              value: "20"
